### ISSUE TITLE
still have error adding package to Julia 1.1

### ISSUE THREAD

**Issue by AlexYoooooo** [sglyon/ORCA.jl#10]
similar problem with https://github.com/sglyon/ORCA.jl/issues/8, however it is still not fixed in Linux 

┌ Error: Error building `ORCA`: 
│ Warning: 'plotly' already in 'channels' list, moving to the top
│ Solving environment: ...working... failed
│ 
│ PackagesNotFoundError: The following packages are not available from current channels:
│ 
│   - plotly-orca
│ 
│ Current channels:
│ 
│   - https://conda.anaconda.org/plotly/linux-32
│   - https://conda.anaconda.org/plotly/noarch
│   - https://repo.anaconda.com/pkgs/main/linux-32
│   - https://repo.anaconda.com/pkgs/main/noarch
│   - https://repo.anaconda.com/pkgs/free/linux-32
│   - https://repo.anaconda.com/pkgs/free/noarch
│   - https://repo.anaconda.com/pkgs/r/linux-32
│   - https://repo.anaconda.com/pkgs/r/noarch
│   - https://repo.anaconda.com/pkgs/pro/linux-32
│   - https://repo.anaconda.com/pkgs/pro/noarch
│ 
│ To search for alternate channels that may provide the conda package you're
│ looking for, navigate to
│ 
│     https://anaconda.org
│ 
│ and use the search bar at the top of the page.
│ 
│ 
│ [ Info: Running `conda config --add channels plotly --file /home/alex/.julia/conda/3/envs/_ORCA_jl_/condarc-julia.yml --force` in _ORCA_jl_ environment
│ [ Info: Running `conda install -y plotly-orca` in _ORCA_jl_ environment
│ ERROR: LoadError: failed process: Process(setenv(`/home/alex/.julia/conda/3/bin/conda install -y plotly-orca`,["GNOME_DESKTOP_SESSION_ID=this-is-deprecated", "DESKTOP_SESSION=ubuntu", "GTK_MODULES=gail:atk-bridge:unity-gtk-module", "UNITY_HAS_3D_SUPPORT=true", "LANG=en_CA.UTF-8", "XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0", "LESSOPEN=| /usr/bin/lesspipe %s", "UPSTART_EVENTS=xsession started", "GTK_IM_MODULE=ibus", "CONDA_PREFIX=/home/alex/.julia/conda/3/envs/_ORCA_jl_", "GNOME_KEYRING_PID=", "XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0", "XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg", "COMPIZ_CONFIG_PROFILE=ubuntu", "COMPIZ_BIN_PATH=/usr/bin/", "LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:", "QT_QPA_PLATFORMTHEME=appmenu-qt5", "PYTHONIOENCODING=UTF-8", "XDG_SESSION_DESKTOP=ubuntu", "VTE_VERSION=4205", "GTK2_MODULES=overlay-scrollbar", "QT_IM_MODULE=ibus", "IM_CONFIG_PHASE=1", "UPSTART_JOB=unity7", "GDMSESSION=ubuntu", "GPG_AGENT_INFO=/home/alex/.gnupg/S.gpg-agent:0:1", "LANGUAGE=en_CA:en", "DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path", "INSTANCE=", "CONDARC=/home/alex/.julia/conda/3/envs/_ORCA_jl_/condarc-julia.yml", "_=/bin/julia", "XAUTHORITY=/home/alex/.Xauthority", "XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/alex", "TERM=xterm-256color", "SESSION=ubuntu", "XMODIFIERS=@im=ibus", "WINDOWID=77594634", "GNOME_KEYRING_CONTROL=", "MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path", "XDG_SESSION_TYPE=x11", "SHLVL=1", "UNITY_DEFAULT_PROFILE=unity", "QT_ACCESSIBILITY=1", "LOGNAME=alex", "JOB=unity-settings-daemon", "DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-LpMuLeJMH8", "XDG_SESSION_ID=c2", "XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop:/var/lib/snapd/desktop", "XDG_RUNTIME_DIR=/run/user/1000", "XDG_SEAT=seat0", "XDG_CURRENT_DESKTOP=Unity", "USER=alex", "JULIA_LOAD_PATH=@:/tmp/tmpuIquJr", "UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/2060", "SESSION_MANAGER=local/Steak:@/tmp/.ICE-unix/2475,unix/Steak:/tmp/.ICE-unix/2475", "UPSTART_INSTANCE=", "SSH_AUTH_SOCK=/run/user/1000/keyring/ssh", "XDG_VTNR=7", "QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1", "PWD=/home/alex", "GDM_LANG=en_CA", "PATH=/home/alex/bin:/home/alex/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "DISPLAY=:0", "OPENBLAS_MAIN_FREE=1", "QT4_IM_MODULE=xim", "XDG_MENU_PREFIX=gnome-", "SHELL=/bin/bash", "HOME=/home/alex", "CLUTTER_IM_MODULE=xim", "LESSCLOSE=/usr/bin/lesspipe %s %s", "SESSIONTYPE=gnome-session"]), ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at ./error.jl:42
│  [2] pipeline_error at ./process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at ./process.jl:726
│  [4] run at ./process.jl:724 [inlined]
│  [5] runconda(::Cmd, ::Symbol) at /home/alex/.julia/packages/Conda/CpuvI/src/Conda.jl:113
│  [6] add(::String, ::Symbol) at /home/alex/.julia/packages/Conda/CpuvI/src/Conda.jl:183
│  [7] top-level scope at none:0
│  [8] include at ./boot.jl:326 [inlined]
│  [9] include_relative(::Module, ::String) at ./loading.jl:1038
│  [10] include(::Module, ::String) at ./sysimg.jl:29
│  [11] include(::String) at ./client.jl:403
│  [12] top-level scope at none:0
│ in expression starting at /home/alex/.julia/packages/ORCA/qEy7Y/deps/build.jl:5
└ @ Pkg.Operations /buildworker/worker/package_linux32/build/usr/share/julia/stdlib/v1.1/Pkg/src/Operations.jl:1075

**Comment by sglyon** [comment]
It looks like you are on a 32 bit system, is that correct?

If so, I think we are unfortunately out of luck here.

**Comment by AlexYoooooo** [comment]
No, but I might actually installed a 32bit julia, let me check

**Comment by AlexYoooooo** [comment]
It still want to search 32bit channel after I installed 64bit Julia, is there a way to overwrite it?

**Comment by sglyon** [comment]
Not sure. Perhaps configurations survived from the 32 bit version of julia? I would probably attempt to delete conda configs in `~/.julia` if you find any. 

Sorry, not an expert here though

**Comment by AlexYoooooo** [comment]
yes, that works, thanks
