### ISSUE TITLE
can not download plotly-orca-1.2.1

### ISSUE THREAD

**Issue by flystar233** [sglyon/ORCA.jl#11]
0% stay here forever~~~
![TIM截图20190402213326](https://user-images.githubusercontent.com/20431495/55406674-24f17900-558f-11e9-8585-992aa0fd5c50.png)

**Comment by flystar233** [comment]
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/plotly/win-64/plotly-orca-1.2.1-1.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

### **I can download files manually on this website. Which folder should I put the downloaded plotly-orca in?**

**Comment by gtollefson** [comment]
@flystar233 It looks like you may be trying to install ORCA.jl on a shared network with a firewall.

**Comment by sglyon** [comment]
Thanks @gtollefson 

@flystar233  I just tried downloading on my  machine and had no problems -- which makes @gtollefson suggestion all the more likely.. can you tell us more about your system?

**Comment by gtollefson** [comment]
I suggested it because I had the same error message when trying to install ORCA.jl on a computer on our shared network. We corrected it by asking our network security team to add bypasses for both:

conda.anaconda.org
repo.anaconda.com

**Comment by sglyon** [comment]
Thanks @gtollefson and @flystar233 

Due to the problems with this package, we have decided to go another direction. The savefig functionality offered by this package has been superseded by new routines built in to PlotlyBase.jl (and thus PlotlyJS.jl) itself.

ORCA.jl is now deprecated and should not be used going forward.

Thank you
