### ISSUE TITLE
Error saving large plot

### ISSUE THREAD

**Issue by gtollefson** [sglyon/ORCA.jl#12]
I receive the following error when saving a PlotlyJS.jl plot as an html file using PlotlyJS.savehtml which seems to use savefig_orca.jl. I am running Julia v1.1.0, ORCA.jl version = "0.2.1", and PlotlyJS.jl version = "0.12.3" on a Macbook Pro running High Sierra 10.13.6. 

Are you able to tell me why this is occuring? Perhaps the plot is too large to save? This has occurred several times consecutively. The code works when saving other plots to html. Saving the offending plot object as a pdf, instead, does work - which supports this being an issue with the way PlotlyJS.savehtml() behaves with this large plot. Interestingly, the html file is created and is able to be opened. The error occurs after it's saved.

> 
> Saving read depth heatmap
> ┌ Warning: Error in @async writebody task
> │   exception =
> │    IOError: write: broken pipe (EPIPE)
> │    Stacktrace:
> │     [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
> │     [2] wait() at ./event.jl:255
> │     [3] uv_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:853
> │     [4] unsafe_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:901
> │     [5] unsafe_write at /Users/George/.julia/packages/HTTP/YjRCz/src/ConnectionPool.jl:136 [inlined]
> │     [6] unsafe_write(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::Ptr{UInt8}, ::UInt64) at /Users/George/.julia/packages/HTTP/YjRCz/src/Streams.jl:95
> │     [7] macro expansion at ./io.jl:509 [inlined]
> │     [8] write at ./io.jl:532 [inlined]
> │     [9] writebody(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::HTTP.Messages.Request, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:100
> │     [10] (::getfield(HTTP.StreamRequest, Symbol("##2#3")){HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Messages.Request,String})() at ./task.jl:259
> └ @ HTTP.StreamRequest ~/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:60
> ┌ Warning: Error in @async writebody task
> │   exception =
> │    IOError: write: broken pipe (EPIPE)
> │    Stacktrace:
> │     [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
> │     [2] wait() at ./event.jl:255
> │     [3] uv_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:853
> │     [4] unsafe_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:901
> │     [5] unsafe_write at /Users/George/.julia/packages/HTTP/YjRCz/src/ConnectionPool.jl:136 [inlined]
> │     [6] unsafe_write(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::Ptr{UInt8}, ::UInt64) at /Users/George/.julia/packages/HTTP/YjRCz/src/Streams.jl:95
> │     [7] macro expansion at ./io.jl:509 [inlined]
> │     [8] write at ./io.jl:532 [inlined]
> │     [9] writebody(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::HTTP.Messages.Request, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:100
> │     [10] (::getfield(HTTP.StreamRequest, Symbol("##2#3")){HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Messages.Request,String})() at ./task.jl:259
> └ @ HTTP.StreamRequest ~/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:60
> ┌ Warning: Error in @async writebody task
> │   exception =
> │    IOError: write: broken pipe (EPIPE)
> │    Stacktrace:
> │     [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
> │     [2] wait() at ./event.jl:255
> │     [3] uv_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:853
> │     [4] unsafe_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:901
> │     [5] unsafe_write at /Users/George/.julia/packages/HTTP/YjRCz/src/ConnectionPool.jl:136 [inlined]
> │     [6] unsafe_write(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::Ptr{UInt8}, ::UInt64) at /Users/George/.julia/packages/HTTP/YjRCz/src/Streams.jl:95
> │     [7] macro expansion at ./io.jl:509 [inlined]
> │     [8] write at ./io.jl:532 [inlined]
> │     [9] writebody(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::HTTP.Messages.Request, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:100
> │     [10] (::getfield(HTTP.StreamRequest, Symbol("##2#3")){HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Messages.Request,String})() at ./task.jl:259
> └ @ HTTP.StreamRequest ~/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:60
> ┌ Warning: Error in @async writebody task
> │   exception =
> │    IOError: write: broken pipe (EPIPE)
> │    Stacktrace:
> │     [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
> │     [2] wait() at ./event.jl:255
> │     [3] uv_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:853
> │     [4] unsafe_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:901
> │     [5] unsafe_write at /Users/George/.julia/packages/HTTP/YjRCz/src/ConnectionPool.jl:136 [inlined]
> │     [6] unsafe_write(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::Ptr{UInt8}, ::UInt64) at /Users/George/.julia/packages/HTTP/YjRCz/src/Streams.jl:95
> │     [7] macro expansion at ./io.jl:509 [inlined]
> │     [8] write at ./io.jl:532 [inlined]
> │     [9] writebody(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::HTTP.Messages.Request, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:100
> │     [10] (::getfield(HTTP.StreamRequest, Symbol("##2#3")){HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Messages.Request,String})() at ./task.jl:259
> └ @ HTTP.StreamRequest ~/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:60
> ┌ Warning: Error in @async writebody task
> │   exception =
> │    IOError: write: broken pipe (EPIPE)
> │    Stacktrace:
> │     [1] try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./event.jl:196
> │     [2] wait() at ./event.jl:255
> │     [3] uv_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:853
> │     [4] unsafe_write(::Sockets.TCPSocket, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:901
> │     [5] unsafe_write at /Users/George/.julia/packages/HTTP/YjRCz/src/ConnectionPool.jl:136 [inlined]
> │     [6] unsafe_write(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::Ptr{UInt8}, ::UInt64) at /Users/George/.julia/packages/HTTP/YjRCz/src/Streams.jl:95
> │     [7] macro expansion at ./io.jl:509 [inlined]
> │     [8] write at ./io.jl:532 [inlined]
> │     [9] writebody(::HTTP.Streams.Stream{HTTP.Messages.Response,HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}, ::HTTP.Messages.Request, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:100
> │     [10] (::getfield(HTTP.StreamRequest, Symbol("##2#3")){HTTP.ConnectionPool.Transaction{Sockets.TCPSocket},HTTP.Messages.Request,String})() at ./task.jl:259
> └ @ HTTP.StreamRequest ~/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:60
> ERROR: LoadError: IOError(Base.IOError("write: broken pipe (EPIPE)", -32) during request(http://localhost:7982))
> 
> Stacktrace:
>  [1] #request#1(::Nothing, ::Nothing, ::Int64, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:status_exception,),Tuple{Bool}}}, ::Function, ::Type{HTTP.StreamRequest.StreamLayer}, ::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Messages.Request, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/StreamRequest.jl:79
>  [2] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction, :status_exception),Tuple{Nothing,Bool}}, ::typeof(HTTP.request), ::Type{HTTP.StreamRequest.StreamLayer}, ::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, ::HTTP.Messages.Request, ::String) at ./none:0
>  [3] #request#1(::Nothing, ::Type, ::Int64, ::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :status_exception),Tuple{Nothing,Bool}}}, ::Function, ::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/ConnectionRequest.jl:52
>  [4] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:iofunction, :status_exception),Tuple{Nothing,Bool}}, ::typeof(HTTP.request), ::Type{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}, ::HTTP.URIs.URI, ::HTTP.Messages.Request, ::String) at ./none:0
>  [5] (::getfield(Base, Symbol("###48#49#50")){ExponentialBackOff,getfield(HTTP.RetryRequest, Symbol("##2#3")){Bool,HTTP.Messages.Request},typeof(HTTP.request)})(::Base.Iterators.Pairs{Symbol,Union{Nothing, Bool},Tuple{Symbol,Symbol},NamedTuple{(:iofunction, :status_exception),Tuple{Nothing,Bool}}}, ::Function, ::Type, ::Vararg{Any,N} where N) at ./error.jl:244
>  [6] ##48#51 at ./none:0 [inlined]
>  [7] #request#1 at /Users/George/.julia/packages/HTTP/YjRCz/src/RetryRequest.jl:44 [inlined]
>  [8] #request at ./none:0 [inlined]
>  [9] #request#1(::VersionNumber, ::String, ::Nothing, ::Nothing, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:status_exception,),Tuple{Bool}}}, ::Function, ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/MessageRequest.jl:47
>  [10] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:status_exception,),Tuple{Bool}}, ::typeof(HTTP.request), ::Type{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at ./none:0
>  [11] #request#1(::Int64, ::Bool, ::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:status_exception,),Tuple{Bool}}}, ::Function, ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/RedirectRequest.jl:24
>  [12] (::getfield(HTTP, Symbol("#kw##request")))(::NamedTuple{(:status_exception,),Tuple{Bool}}, ::typeof(HTTP.request), ::Type{HTTP.RedirectRequest.RedirectLayer{HTTP.MessageRequest.MessageLayer{HTTP.RetryRequest.RetryLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}}}, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at ./none:0
>  [13] #request#3(::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:status_exception,),Tuple{Bool}}}, ::Function, ::String, ::HTTP.URIs.URI, ::Array{Pair{SubString{String},SubString{String}},1}, ::String) at /Users/George/.julia/packages/HTTP/YjRCz/src/HTTP.jl:302
>  [14] #request at ./none:0 [inlined]
>  [15] #request#4 at /Users/George/.julia/packages/HTTP/YjRCz/src/HTTP.jl:316 [inlined]
>  [16] #request at ./none:0 [inlined]
>  [17] #post#8 at /Users/George/.julia/packages/HTTP/YjRCz/src/HTTP.jl:363 [inlined]
>  [18] #post at ./none:0 [inlined]
>  [19] #savefig#1(::SubString{String}, ::Nothing, ::Nothing, ::Nothing, ::Function, ::IOStream, ::Plot{GenericTrace{Dict{Symbol,Any}}}) at /Users/George/.julia/packages/ORCA/qEy7Y/src/ORCA.jl:35
>  [20] (::getfield(PlotlyBase, Symbol("#kw##savefig")))(::NamedTuple{(:format, :scale, :width, :height),Tuple{SubString{String},Nothing,Nothing,Nothing}}, ::typeof(savefig), ::IOStream, ::Plot{GenericTrace{Dict{Symbol,Any}}}) at ./none:0
>  [21] (::getfield(ORCA, Symbol("##3#4")){Nothing,Nothing,Nothing,Plot{GenericTrace{Dict{Symbol,Any}}}})(::IOStream) at /Users/George/.julia/packages/ORCA/qEy7Y/src/ORCA.jl:71
>  [22] #open#310(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::getfield(ORCA, Symbol("##3#4")){Nothing,Nothing,Nothing,Plot{GenericTrace{Dict{Symbol,Any}}}}, ::String, ::Vararg{String,N} where N) at ./iostream.jl:369
>  [23] open at ./iostream.jl:367 [inlined]
>  [24] #savefig#2 at /Users/George/.julia/packages/ORCA/qEy7Y/src/ORCA.jl:70 [inlined]
>  [25] savefig(::Plot{GenericTrace{Dict{Symbol,Any}}}, ::String) at /Users/George/.julia/packages/ORCA/qEy7Y/src/ORCA.jl:65
>  [26] #savefig#50(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::PlotlyJS.SyncPlot, ::String) at /Users/George/.julia/packages/PlotlyJS/CEJyh/src/savefig_orca.jl:1
>  [27] savefig at /Users/George/.julia/packages/PlotlyJS/CEJyh/src/savefig_orca.jl:1 [inlined]
>  [28] save_graphic(::PlotlyJS.SyncPlot, ::String, ::String, ::String, ::Bool) at /Users/George/.julia/dev/VariantVisualization/src/vcf_utils_complete.jl:1599
>  [29] top-level scope at /Users/George/.julia/dev/VariantVisualization/viva:427
>  [30] include at ./boot.jl:326 [inlined]
>  [31] include_relative(::Module, ::String) at ./loading.jl:1038
>  [32] include(::Module, ::String) at ./sysimg.jl:29
>  [33] exec_options(::Base.JLOptions) at ./client.jl:267
>  [34] _start() at ./client.jl:436
> in expression starting at /Users/George/.julia/dev/VariantVisualization/viva:354
> 
> 
> 
> 
>

**Comment by sglyon** [comment]
Could you provide an example of code that generates a plot where `PlotlyJS.savehtml` fails?

**Comment by sglyon** [comment]
Thanks for reporting @gtollefson 

Due to the problems with this package, we have decided to go another direction. The savefig functionality offered by this package has been superseded by new routines built in to PlotlyBase.jl (and thus PlotlyJS.jl) itself.

ORCA.jl is now deprecated and should not be used going forward.

Thank you
