### ISSUE TITLE
Issue Builiding ORCA

### ISSUE THREAD

**Issue by anthonyagudelox3** [sglyon/ORCA.jl#16]
When I have attempted building ORCA, I recieve the following error message, I was wondering if you have any inclination as to why this is? I am currently running Windows 10 64bit, on Julia v1.1.1. 
I have tried deleting Julia and reinstalling it and I still recieve the following error message:

>   Building ORCA ─────→ `C:\Users\Thor\.julia\packages\ORCA\qEy7Y\deps\build.log`
┌ Error: Error building `ORCA`, showing the last 100 of log:
│     openssl-1.1.1c             |       he774522_1         5.7 MB
│     python-libarchive-c-2.8    |          py36_11          23 KB
│     tqdm-4.32.1                |             py_0          48 KB
│     lzo-2.10                   |       h6df0209_2         154 KB
│     ca-certificates-2019.5.15  |                0         166 KB
│     libarchive-3.3.3           |       h0643e63_5         1.4 MB
│     vc-14.1                    |       h0510ff6_4           6 KB
│     libiconv-1.15              |       h1df5818_7         664 KB
│     zstd-1.3.7                 |       h508b16e_0         536 KB
│     ------------------------------------------------------------
│                                            Total:        19.9 MB
│
│ The following NEW packages will be INSTALLED:
│
│     bzip2:                  1.0.8-he774522_0
│     conda-package-handling: 1.3.11-py36_0
│     libarchive:             3.3.3-h0643e63_5
│     libiconv:               1.15-h1df5818_7
│     libxml2:                2.9.9-h464c3ec_0
│     lz4-c:                  1.8.1.2-h2fa13f4_0
│     lzo:                    2.10-h6df0209_2
│     python-libarchive-c:    2.8-py36_11
│     tqdm:                   4.32.1-py_0
│     xz:                     5.2.4-h2fa13f4_4
│     zlib:                   1.2.11-h62dcd97_3
│     zstd:                   1.3.7-h508b16e_0
│
│ The following packages will be UPDATED:
│
│     ca-certificates:        2018.03.07-0         --> 2019.5.15-0
│     certifi:                2018.4.16-py36_0     --> 2019.6.16-py36_1
│     conda:                  4.5.4-py36_0         --> 4.7.10-py36_0
│     cryptography:           2.2.2-py36hfa6e2cd_0 --> 2.7-py36h7a1dbc1_0
│     openssl:                1.0.2o-h8ea7d77_0    --> 1.1.1c-he774522_1
│     vc:                     14-h0510ff6_3        --> 14.1-h0510ff6_4
│     vs2015_runtime:         14.0.25123-3         --> 14.15.26706-h3a45250_4
│
│
│ Downloading and Extracting Packages
│ Preparing transaction: ...working... done
│ Verifying transaction: ...working... done
│ Executing transaction: ...working... done
│
│ Collecting package metadata (current_repodata.json): ...working... done
│ Solving environment: ...working... done
│
│ ## Package Plan ##
│
│   environment location: C:\Users\Thor\.julia\conda\3\envs\_ORCA_jl_
│
│
│
│ Preparing transaction: ...working... done
│ Verifying transaction: ...working... done
│ Executing transaction: ...working... done
│ #
│ # To activate this environment, use
│ #
│ #     $ conda activate C:\Users\Thor\.julia\conda\3\envs\_ORCA_jl_
│ #
│ # To deactivate an active environment, use
│ #
│ #     $ conda deactivate
│
│ Collecting package metadata (current_repodata.json): ...working... failed
│
│ CondaHTTPError: HTTP 504 GATEWAY_TIMEOUT for url <https://conda.anaconda.org/plotly/win-64/current_repodata.json>
│ Elapsed: 00:59.512266
│ CF-RAY: 4fe8e1aabf39c5e4-EWR
│
│ A remote server error occurred when trying to retrieve this URL.
│
│ A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
│ fulfill a valid request.  The problem may be spurious, and will resolve itself if you
│ try your request again.  If the problem persists, consider notifying the maintainer
│ of the remote server.
│
│
│ [ Info: Downloading miniconda installer ...
│ [ Info: Installing miniconda ...
│ [ Info: Running `conda config --add channels defaults --file 'C:\Users\Thor\.julia\conda\3\condarc-julia.yml' --force` in root environment
│ [ Info: Running `conda update -y conda` in root environment
│ [ Info: Running `conda create -y -p 'C:\Users\Thor\.julia\conda\3\envs\_ORCA_jl_'` in root environment
│ [ Info: Running `conda config --add channels plotly --file 'C:\Users\Thor\.julia\conda\3\envs\_ORCA_jl_\condarc-julia.yml' --force` in _ORCA_jl_ environment
│ [ Info: Running `conda install -y plotly-orca` in _ORCA_jl_ environment
│ ERROR: LoadError: failed process: Process(setenv(`'C:\Users\Thor\.julia\conda\3\Scripts\conda.exe' install -y plotly-orca`,["USERDOMAIN_ROAMINGPROFILE=DESKTOP-55UEM3R", "HOMEPATH=\\Users\\Thor", "ProgramData=C:\\ProgramData", "ProgramW6432=C:\\Program Files", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL", "SESSIONNAME=Console", "APPDATA=C:\\Users\\Thor\\AppData\\Roaming", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=DESKTOP-55UEM3R", "OS=Windows_NT", "PROCESSOR_REVISION=8e09", "TMP=C:\\Users\\Thor\\AppData\\Local\\Temp", "ALLUSERSPROFILE=C:\\ProgramData", "Path=C:\\ProgramData\\DockerDesktop\\version-bin;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\Thor\\AppData\\Local\\Julia-1.1.1\\bin;C:\\Program Files (x86)\\Java\\jre1.8.0_211\\bin;C:E=DESKTOP-55UEM3R", "USERNAME=Thor", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "CommonProgramFiles=C:\\Program Fil
es\\Common Files", "CONDARC=C:\\Users\\Thor\\.julia\\conda\\3\\envs\\_ORCA_jl_\\condarc-julia.yml", "USERPROFILE=C:\\Users\\Thor", "PSMod
ulePath=C:\\Users\\Thor\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\Windo
wsPowerShell\\v1.0\\Modules", "PROCESSOR_LEVEL=6", "=C:=C:\\Users\\Thor\\.julia\\packages\\ORCA\\qEy7Y\\deps", "TEMP=C:\\Users\\Thor\\App
Data\\Local\\Temp", "SystemDrive=C:", "HOMEDRIVE=C:", "PYTHONIOENCODING=UTF-8", "LOCALAPPDATA=C:\\Users\\Thor\\AppData\\Local", "PROCESSO
R_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 9, GenuineIntel", "DriverData=C:\\Windows\\System32\\Drivers\\DriverData", "NUMBER_OF_PR
OCESSORS=4", "=::=::\\", "ComSpec=C:\\WINDOWS\\system32\\cmd.exe", "SystemRoot=C:\\WINDOWS", "OneDrive=C:\\Users\\Thor\\OneDrive", "OneDr
iveConsumer=C:\\Users\\Thor\\OneDrive", "ProgramFiles(x86)=C:\\Program Files (x86)", "LOGONSERVER=\\\\DESKTOP-55UEM3R", "CONDA_PREFIX=C:\
\Users\\Thor\\.julia\\conda\\3\\envs\\_ORCA_jl_", "windir=C:\\WINDOWS", "JULIA_LOAD_PATH=@;C:\\Users\\Thor\\AppData\\Local\\Temp\\jl_1BBC
.tmp", "CommonProgramW6432=C:\\Program Files\\Common Files", "ProgramFiles=C:\\Program Files", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_
MAIN_FREE=1"]), ProcessExited(1)) [1]
│ Stacktrace:
│  [1] error(::String, ::Base.Process, ::String, ::Int64, ::String) at .\error.jl:42
│  [2] pipeline_error at .\process.jl:785 [inlined]
│  [3] #run#515(::Bool, ::Function, ::Cmd) at .\process.jl:726
│  [4] run at .\process.jl:724 [inlined]
│  [5] runconda(::Cmd, ::Symbol) at C:\Users\Thor\.julia\packages\Conda\kLXeC\src\Conda.jl:113
│  [6] #add#1(::String, ::Function, ::String, ::Symbol) at C:\Users\Thor\.julia\packages\Conda\kLXeC\src\Conda.jl:184
│  [7] add(::String, ::Symbol) at C:\Users\Thor\.julia\packages\Conda\kLXeC\src\Conda.jl:183
│  [8] top-level scope at none:0
│  [9] include at .\boot.jl:326 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1038
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:403
│  [13] top-level scope at none:0
│ in expression starting at C:\Users\Thor\.julia\packages\ORCA\qEy7Y\deps\build.jl:5
│
│ Full log at C:\Users\Thor\.julia\packages\ORCA\qEy7Y\deps\build.log
└ @

**Comment by sglyon** [comment]
Hmm, that's a strange error. I haven't come across it before and am not sure why you would be seeing it .

Sorry, but I'm afraid I won't be very helpful here

**Comment by anthonyagudelox3** [comment]
I attempted to build ORCA again today and the issue seemed to have fixed itself. I will close the issue. Thank you.

**Comment by behinger** [comment]
I had the same issue. Julia 1.4, win64. 

I digged down deep and it seems to be some kind of conda issue.  a workaround can be found here:
https://github.com/conda/conda/issues/8273

> My workaround:
> I have copied the following files
>
> libcrypto-1_1-x64.*
> libssl-1_1-x64.*
> 
> from D:\Anaconda3\Library\bin to D:\Anaconda3\DLLs.

**Comment by sglyon** [comment]
Should be fixed! We no longer use conda
