### ISSUE TITLE
unable to load ORCA on Arch

### ISSUE THREAD

**Issue by IgorDouven** [sglyon/ORCA.jl#18]
Hi,

I'm unable to load ORCA, getting the following error message:

/home/igor/.julia/conda/3/envs/_ORCA_jl_/lib/orca_app/orca: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

Building the package shows no problems. I'm running Julia 1.1.1 under Arch.

**Comment by sglyon** [comment]
Hmm I don't have a way to test this and I'm not familiar with the error.

Do you have any ideas?

**Comment by IgorDouven** [comment]
No, I wouldn't know. I just tried on Clear Linux, which I have running in
VirtualBox on my mac, and I got exactly the same error message. (And on my
mac, I cannot even add ORCA -- I got the message that it's an unknown
package.) Is there any way to store plots that doesn't require ORCA?

Op vr 16 aug. 2019 om 16:25 schreef Spencer Lyon <notifications@github.com>:

**Comment by sglyon** [comment]
you could store them as html or JSON. all "graphics" formats like png, pdf, svg, jpeg require ORCA

**Comment by IgorDouven** [comment]
No, I'd really need pdf output. Btw, at least from within a Jupyter
notebook, I *can* store them as pngs (but for most journals, that's not
good enough).

Op vr 16 aug. 2019 om 17:53 schreef Spencer Lyon <notifications@github.com>:

**Comment by sglyon** [comment]
I see. I really don't think I'd be able to help on this one

A workaround for now is to save them to json, load them with python and try writing to pdf from there. I'd be a little surprised if that works because Plotly.py also depends on orca, but maybe their method of installation would work better for you

**Comment by IgorDouven** [comment]
Not a problem. Thanks for considering this. The output in the notebook
looks really good, so hopefully in some future release of PlotlyJS/ORCA
this will work for me.

Op vr 16 aug. 2019 om 20:48 schreef Spencer Lyon <notifications@github.com>:

**Comment by dbonattoj** [comment]
Hello,

I had the same problem today
my solution:  sudo pacman -S gconf

Best regards :)

**Comment by IgorDouven** [comment]
It worked -- many thanks!

Op ma 19 aug. 2019 om 12:54 schreef dbonattoj <notifications@github.com>:

**Comment by sglyon** [comment]
Thanks @dbonattoj and @IgorDouven !
