### ISSUE TITLE
savefig to html not working

### ISSUE THREAD

**Issue by pdimens** [sglyon/ORCA.jl#2]
Hello, I'm trying to export a plotly graph into HTML, which I was able to do a few weeks ago without issue, but in trying to do it today, I get an error 
```MethodError: no method matching show(::IOStream, ::MIME{Symbol("text/html")}, ::Plot{GenericTrace{Dict{Symbol,Any}}})```

My code is fairly simple:
``` julia
#! /usr/bin/env julia
using Blink
using PlotlyJS
using CSV
using ORCA
using DataFrames

infile = CSV.read("/home/pdimens/Downloads/queentrigger_2_illumina.csv",delim = ",", header=["lane","project","sample","barcode","reads","percent of lane","percent perfect barcode","percent one mismatch","yield","percent PF clusters","pq30","mqscore"], datarow=8)
function statplots()
    trace1 = bar(;x= infile.sample, y=infile.reads, name = "Number of reads", text = infile.sample)
    trace2 = bar(;x= infile.sample, y=infile.yield, name = "Yield (mbases)")
    trace3 = bar(;x= infile.sample, y=infile.pq30, name = "% > Q30")
    trace4 = bar(;x= infile.sample, y=infile.mqscore, name = "Mean Quality Score")

    layout = Layout(;barmode = "stack", bargap = 0.1, font_size = 6, margin = attr(l=100, r=50, b=50, t=50, pad=10))
    plot([trace1,trace2,trace3,trace4], layout)
end
statplots()
savefig(statplots(), "/home/pdimens/Documents/output_filename.html")
```
Is there now a different way of exporting plotly figures as HTML?

**Comment by rjkat** [comment]
+1

**Comment by rjkat** [comment]
Think I found the issue. See referenced commit. For now, use:
```
PlotlyJS.savehtml(p, "foo.html")
```

**Comment by sglyon** [comment]
@pdimens sorry for the super late response!! I thought I had commented here

@rkat is correct that `savehtml` will work.

We should have an outlet in the `savefig` function that checks for an `html` suffix and calls `savehtml` for you

**Comment by sglyon** [comment]
Thank you @rjkat  and @pdimens 

Due to the problems with this package, we have decided to go another direction. The savefig functionality offered by this package has been superseded by new routines built in to PlotlyBase.jl (and thus PlotlyJS.jl) itself.

ORCA.jl is now deprecated and should not be used going forward.

Thank you
