### ISSUE TITLE
ORCA executable path not correctly escaped on Windows

### ISSUE THREAD

**Issue by EHBaozi** [sglyon/ORCA.jl#21]
On my Windows 10 machine, `deps\paths.jl` reads
```julia
# This file is automatically generated by build.jl DO NOT EDIT
const orca_cmd = `C:\Users\invis\.julia\conda\3\envs\_ORCA_jl_\orca_app\orca.exe`
```
where the backslashes are not escaped properly. This prevents `ORCA.jl` from being loaded into Julia. As an alternative solution, surrounding the path with quotes should also fix it:
```julia
# deps\build.jl, line 24
println(f, "const orca_cmd = `\"$(orca_cmd)\"`")
```

**Comment by BoundaryValueProblems** [comment]
@EHBaozi it would be really great if you could do pull request so that @sglyon can generate a corrected version of PlotlyJS.jl
Thanks!

**Comment by sglyon** [comment]
Thank you all!
