### ISSUE TITLE
Precompilation fails on Windows 10

### ISSUE THREAD

**Issue by BoundaryValueProblems** [sglyon/ORCA.jl#4]
@sglyon , I just installed Julia v1.0 on my Windows 10 machine, and also installed ORCA. I could built ORCA, but precompilation failed as follows:
```Julia
julia> using ORCA
[ Info: Precompiling ORCA [47be7bcc-f1a6-5447-8b36-7eeeff7534fd]
ERROR: LoadError: LoadError: syntax: invalid escape sequence
Stacktrace:
 [1] include at .\boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1038
 [3] include at .\sysimg.jl:29 [inlined]
 [4] include(::String) at C:\Users\xxx\.julia\packages\ORCA\vWe2Y\src\ORCA.jl:1
 [5] top-level scope at C:\Users\xxx\.julia\packages\ORCA\vWe2Y\src\ORCA.jl:12
 [6] include at .\boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1038
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at .\boot.jl:319 [inlined]
 [11] eval(::Expr) at .\client.jl:389
 [12] top-level scope at .\none:3
in expression starting at C:\Users\xxx\.julia\packages\ORCA\vWe2Y\deps\paths.jl:2
in expression starting at C:\Users\xxx\.julia\packages\ORCA\vWe2Y\src\ORCA.jl:7
ERROR: Failed to precompile ORCA [47be7bcc-f1a6-5447-8b36-7eeeff7534fd] to C:\Users\xxx\.julia\compiled\v1.0\ORCA\jvX7k.ji.
Stacktrace:
 [1] macro expansion at .\logging.jl:313 [inlined]
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1184
 [3] macro expansion at .\logging.jl:311 [inlined]
 [4] _require(::Base.PkgId) at .\loading.jl:941
 [5] require(::Base.PkgId) at .\loading.jl:852
 [6] macro expansion at .\logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at .\loading.jl:834
```
Thanks a lot for help!

**Comment by sglyon** [comment]
oh no! Thanks for reporting, will you help me debug? I don't have access to a windows machine so it would be difficult for me to do alone.

That being said, I think I might know what is going on...

The file `deps/build.jl` will install the orca package and then create a file `deps/paths.jl` that has the path on your machine to the downloaded binary.

The lines that make `deps/paths.jl` are (found [here](https://github.com/sglyon/ORCA.jl/blob/daf3f49b3f98fe634b15d996d4f4bcc67a921f81/deps/build.jl#L8-L12))



```Julia
open("paths.jl", "w") do f
    orca_cmd = joinpath(@__DIR__, "bin", "orca")
    println(f, "# This file is automatically generated by build.jl DO NOT EDIT")
    println(f, "const orca_cmd = \"$(orca_cmd)\"")
end
```

I think what is happening is that the `joinpath` command returns a string where paths are separated via `\` as is custom on windows instead of `/`. The issue is that `\` is also used for escape sequences like `\n` or `\t`.

Maybe you could figure out how to solve that?

**Comment by BoundaryValueProblems** [comment]
@sglyon , on my windows machine, the contents of ```deps/paths.jl``` is:
```
# This file is automatically generated by build.jl DO NOT EDIT
const orca_cmd = "C:\Users\My Username\.julia\packages\ORCA\vWe2Y\deps\bin\orca"
```
On the other hand, the contents of ```orca.cmd``` generated in the same directory is:
```
@echo off
"C:/Users/My Username/.julia/packages/ORCA/vWe2Y/deps\orca_app\orca.exe" %*
```
In other words, in ```orca.cmd```, ```/``` and ```\``` are mixed while no mixes in ```paths.jl```.
So, ```jointpath``` command seems to return those path name with ```/``` just like on Mac OS X and Linux. 
I found a posting at Julia forum: https://discourse.julialang.org/t/file-system-paths-in-meta-parse-end-up-in-error-on-windows/14903 .
Would this help you resolve the problem? Thanks!

**Comment by sglyon** [comment]
I think that might work, would you be willing to give it a shot?

I also agree with your idea to only use `/` in paths. Even though that isn't the Windows notation, Julia should still be able to handle it on any platform

**Comment by BoundaryValueProblems** [comment]
@sglyon I replaced the following lines in ```deps/build.jl```:
```
orca_cmd = joinpath(@__DIR__, "bin", "orca")
println(f, "# This file is automatically generated by build.jl DO NOT EDIT")
printf(f, "const orca_cmd = \"$(orca_cmd)\"")
```
by
```
orca_cmd = joinpath(@__DIR__, "orca_app", "orca")
println(f, "# This file is automatically generated by build.jl DO NOT EDIT")
printf(f, "const orca_cmd = $(repr(orca_cmd))")
```
This changed the output file ```paths.jl``` from
```
const orca_cmd = "C:\Users\My Username\.julia\packages\ORCA\vWe2Y\deps\bin\orca"
```
to
```
const orca_cmd = "C:\\Users\\My Username\\.julia\\packages\\ORCA\\vWe2Y\\deps\\orca_app\\orca"
```
However, the resulting ```deps/orca_cmd``` is exactly the same as before: still contains that mixed ```/``` and ```\```, i.e.,
```
@echo off
"C:/Users/My Username/.julia/packages/ORCA/vWe2Y/deps\orca_app\orca.exe" %*
```
This is still incorrect, but somehow I could precompile ORCA. But the changes in ```paths.jl``` are important, i.e., using ```\\``` and ```orca_app``` instead of ```\``` and ```bin```, respectively.
I have no idea why ```deps/bin``` and ```deps/lib``` subfolders were not created on Windows. (On Mac, these two are created, so ```deps/bin/orca``` exists).

So, this is a temporary hack on the windows. Do you know why all these executables and library files are put under a single folder ```orca_app``` on Windows while on Mac (and most likely on Linux too) they are nicely organized into ```bin``` and ```lib```?

**Comment by sglyon** [comment]
Hi @BoundaryValueProblems thanks for looking into this. It's too bad that the windows and unix ocra installs are structured differently. If you are up for it, I think you are in a much better position than I to find a solution that will work for windows. 

The code that I included does indeed work on linux and Mac, so it could be left as is on master, but put beneath a `if Sys.isunix()` and a solution that we (you) come up with can go in the `else` branch.

Thanks again for looking into it!

**Comment by BoundaryValueProblems** [comment]
@sglyon: I modified ```build.jl``` as follows, and this seems to work both on Mac and Windows (I haven't tested on Linux machine yet, but most likely it should work). Since this is a tiny modification on a single file, I don't want to do official pull request. Hence, could you update ```build.jl``` when you release the next version of ```ORCA.jl```? Of course, please test this on your own machine before updating the repository. Thanks a lot!
```
using Conda

env = @__DIR__
Conda.add_channel("plotly", env)
Conda.add("plotly-orca", env)
Conda.update(env)

if Sys.isunix()
    bindir = "bin"
else # assuming Windows
    bindir = "orca_app"
end

open("paths.jl", "w") do f
    orca_cmd = joinpath(@__DIR__, bindir, "orca")
    println(f, "# This file is automatically generated by build.jl DO NOT EDIT")
    println(f, "const orca_cmd = $(repr(orca_cmd))")
end
```

**Comment by sglyon** [comment]
Thanks for figuring this out and testing it. 

I would strongly prefer that you do a pull request as that would ensure this works on Linux also. Could you please do that?

Thank you

**Comment by BoundaryValueProblems** [comment]
@sglyon: OK, I just did the pull request. Hope it works!

**Comment by sglyon** [comment]
Thank you very much! I think we are in good shape.

I will publish a new release today

**Comment by BoundaryValueProblems** [comment]
@sglyon ; ORCA was working for a while on Windows 10 machine, but after I installed v0.3.0, it failed to precompile again with the following error. All these Windows specific directory names look incorrect. In particular all \ are missing. Can you check the previous version and modify it so that it correctly precompiles on Windows 10 machines? Thanks!
```
using Plots, ORCA
[ Info: Precompiling ORCA [47be7bcc-f1a6-5447-8b36-7eeeff7534fd]
ERROR: InitError: IOError: could not spawn `C:Usersxxx.juliaconda3envs_ORCA_jl_orca_apporca.exe server --port=7982 --graph-only`: no such file or directory (ENOENT)
```

**Comment by dcelisgarza** [comment]
I've had a similar problem. Here is the info i have.

```
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 7 1700 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, znver1)
Environment:
  JULIA_EDITOR = "C:\Users\user\AppData\Local\atom\app-1.45.0\atom.exe"  -a
  JULIA_NUM_THREADS = 16
```

Here is the precompilation error:

```
julia> plotlyjs()
[ Info: Precompiling ORCA [47be7bcc-f1a6-5447-8b36-7eeeff7534fd]
ERROR: LoadError: ORCA not installed properly. Please call `Pkg.build("ORCA")`
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] top-level scope at C:\Users\user\.julia\packages\ORCA\fiEmb\src\ORCA.jl:10
 [3] include(::Module, ::String) at .\Base.jl:377
 [4] top-level scope at none:2
 [5] eval at .\boot.jl:331 [inlined]
 [6] eval(::Expr) at .\client.jl:449
 [7] top-level scope at .\none:3
in expression starting at C:\Users\user\.julia\packages\ORCA\fiEmb\src\ORCA.jl:7
ERROR: Failed to precompile ORCA [47be7bcc-f1a6-5447-8b36-7eeeff7534fd] to C:\Users\user\.julia\compiled\v1.4\ORCA\jvX7k_HDBhD.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
 [6] top-level scope at C:\Users\user\.julia\packages\Plots\vTdnV\src\backends.jl:472
 [7] eval at .\boot.jl:331 [inlined]
 [8] _initialize_backend(::Plots.PlotlyJSBackend) at C:\Users\user\.julia\packages\Plots\vTdnV\src\backends.jl:471
 [9] backend at C:\Users\user\.julia\packages\Plots\vTdnV\src\backends.jl:176 [inlined]
 [10] plotlyjs(; kw::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at C:\Users\user\.julia\packages\Plots\vTdnV\src\backends.jl:33
 [11] plotlyjs() at C:\Users\user\.julia\packages\Plots\vTdnV\src\backends.jl:33
 [12] top-level scope at none:0
 ```

After trying to build:

```
julia> Pkg.build("ORCA")
   Building Conda → `C:\Users\user\.julia\packages\Conda\3rPhK\deps\build.log`
   Building ORCA ─→ `C:\Users\user\.julia\packages\ORCA\fiEmb\deps\build.log`
┌ Error: Error building `ORCA`:
│ Warning: 'plotly' already in 'channels' list, moving to the top
│ Collecting package metadata (current_repodata.json): ...working... failed
│ 
│ CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/plotly/win-64/current_repodata.json>
│ Elapsed: -
│ 
│ An HTTP error occurred when trying to retrieve this URL.
│ HTTP errors are often intermittent, and a simple retry will get you on your way.
│ 'https://conda.anaconda.org/plotly/win-64'
│ 
│ 
│ [ Info: Running `conda config --add channels plotly --file 'C:\Users\user\.julia\conda\3\envs\_ORCA_jl_\condarc-julia.yml' --force` in _ORCA_jl_ environment
│ [ Info: Running `conda install -y plotly-orca` in _ORCA_jl_ environment
│ ERROR: LoadError: failed process: Process(setenv(`'C:\Users\user\.julia\conda\3\Scripts\conda.exe' install -y plotly-orca`,["PATH=C:\\Users\\user\\.julia\\conda\\3\\envs\\_ORCA_jl_\\Library\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;D:\\Matlab\\R2020a\\runtime\\win64;D:\\Matlab\\R2020a\\bin;C:\\Users\\user\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\user\\AppData\\Local\\atom\\bin;C:\\Users\\user\\AppData\\Local\\GitHubDesktop\\bin", "USERDOMAIN_ROAMINGPROFILE=DESKTOP-Q87AM7Q", "HOMEPATH=\\Users\\user", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "NODE_ENV=production", "SESSIONNAME=Console", "GKS_USE_CAIRO_PNG=true", "APPDATA=C:\\Users\\user\\AppData\\Roaming", "PSMODULEPATH=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules", "SYSTEMROOT=C:\\WINDOWS"  …
"PROGRAMFILES=C:\\Program Files", "GKS_FONTPATH=C:\\Users\\user\\.julia\\packages\\GR\\yMV3y\\src\\..\\deps\\gr", "LOGONSERVER=\\\\DESKTOP-Q87AM7Q", "CONDA_PREFIX=C:\\Users\\user\\.julia\\conda\\3\\envs\\_ORCA_jl_", "ATOM_HOME=C:\\Users\\user\\.atom", "AMDRMSDKPATH=C:\\Program Files\\AMD\\RyzenMasterSDK\\", "JULIA_LOAD_PATH=@;C:\\Users\\DANIEL~1\\AppData\\Local\\Temp\\jl_TolxHb", "SYSTEMDRIVE=C:", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
│ 
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:525 [inlined]
│  [2] run(::Cmd; wait::Bool) at .\process.jl:440
│  [3] run at .\process.jl:438 [inlined]
│  [4] runconda(::Cmd, ::Symbol) at C:\Users\user\.julia\packages\Conda\3rPhK\src\Conda.jl:114
│  [5] add(::String, ::Symbol; channel::String) at C:\Users\user\.julia\packages\Conda\3rPhK\src\Conda.jl:188
│  [6] add(::String, ::Symbol) at C:\Users\user\.julia\packages\Conda\3rPhK\src\Conda.jl:187
│  [7] top-level scope at C:\Users\user\.julia\packages\ORCA\fiEmb\deps\build.jl:5
│  [8] include(::String) at .\client.jl:439
│  [9] top-level scope at none:5
│ in expression starting at C:\Users\user\.julia\packages\ORCA\fiEmb\deps\build.jl:5
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892
```

The website [https://conda.anaconda.org/plotly/win-64/current_repodata.json](https://conda.anaconda.org/plotly/win-64/current_repodata.json) which throws the HTTP error does indeed lead to a blank site.

I recently updated to Julia 1.4 and this is when the problem started. Is there a way to manually install `ORCA`?

**Comment by sglyon** [comment]
Hmm I just verified that this is happening too.

I'm not sure why. 

I checked out the plotly/orca readme and it does have instructions for downloading the binary without needing to use conda (see [here](https://github.com/plotly/orca#method-4-standalone-binaries))

I don't have the bandwidth right now to figure out how to get this set up, but would happily review and merge any pull requests that are able to take the steps outlined in the plotly/orca readme and put them into a julia script that we can run instead of the Conda.jl code in [deps/build.jl](https://github.com/sglyon/ORCA.jl/blob/7f79836dac957c7b4e1a8a14dbc71620854115b0/deps/build.jl)

**Comment by sglyon** [comment]
Thanks @BoundaryValueProblems @dcelisgarza 

Due to the problems with this package, we have decided to go another direction. The savefig functionality offered by this package has been superseded by new routines built in to PlotlyBase.jl (and thus PlotlyJS.jl) itself.

ORCA.jl is now deprecated and should not be used going forward.

Thank you

**Comment by BoundaryValueProblems** [comment]
Thanks a lot for your effort, @sglyon! OK, when I updated PlotlyJS.jl, and tried to use it, it generated the following warning:
```
[ Info: Precompiling ORCA [47be7bcc-f1a6-5447-8b36-7eeeff7534fd]
┌ Warning: ORCA.jl has been deprecated and all savefig functionality
│ has been implemented directly in PlotlyBase itself.
│ 
│ By implementing in PlotlyBase.jl, the savefig routines are automatically
│ available to PlotlyJS.jl also.
└ @ ORCA ~/.julia/packages/ORCA/U5XaN/src/ORCA.jl:8
```
Now, can I remove ORCA package completely? I am wondering why ORCA was precompiled when I tried to use PlotlyJS...

**Comment by sglyon** [comment]
Yeah let’s remove ORCA entirely 

You should see PlotlyJS version 0.14 and PlotlyBase version at least 0.4
